### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [zameekron/prj-rev-bwfs-dasmoto#6]
https://github.com/zameekron/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/Resources/css/style.css#L10-L35

You're repeating a lot of code here.

All of the `h2` tags have some basic styles shared between them. You should put these styles into a single selector so that they're not repeated in every single CSS rule.

```css
h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}
```

The font-family should be applied the same all elements on the page. Use the universal selector `*` to do this in a single CSS rule.

```css
* {
  font-family: Helvetica;
}
```
